name: logicat-heart-beat
title: Logicat Heart Beat
base: core20
architectures:
  - build-on: amd64
    run-on:  amd64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
version: '2.1.0'
summary: Simple node.js, snap heart beat for logicat-iot Cloud Platform
description: |
  Simple node.js, snap heart beat for logicat-iot Cloud Platform. The heart beat
  raiting is set with an environment variable.

type: app
icon: logicat.png
license: ISC
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  node-service:
    command: bin/logicat-heart-beat
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs: [network]

parts:
  node-service:
    source: .
    plugin: npm
    npm-node-version: '14.17.6'
    # fix the npm root problem by set the npm_config_unsafe_perm
    build-environment:
    - npm_config_unsafe_perm: 'true'
    # stage-packages:
    #  - libatomic1